name: tulip

services:
  proxy:
    image: traefik:v2.10
    container_name: tulip_proxy
    ports:
      - "80:80"
      - "443:443"
      - "8855:8080"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - ./config/traefik/traefik.yml:/etc/traefik/traefik.yml
    networks:
      - tulip
    restart: unless-stopped

networks:
  tulip:
    external: true
