api:
  dashboard: true
  insecure: true

entryPoints:
  web:
    address: ":80"
  websecure:
    address: ":443"

providers:
  docker:
    endpoint: "unix:///var/run/docker.sock"
    exposedByDefault: false
    network: traefik
    defaultRule: "Host(`{{ index .Labels \"project.domain\" }}`) || Host(`{{ index .Labels \"com.docker.compose.service\" }}.{{ index .Labels \"com.docker.compose.project\" }}.loc`)"
  file:
    directory: "/etc/traefik/config/dynamic"
    watch: true

log:
  level: "INFO"
